### ISSUE TITLE
BaseLazyFragment的几个问题

### ISSUE THREAD

**Issue by hush881025** [SkillCollege/SimplifyReader#11]
1.成员变量isPrepared有什么用，感觉没有啥用？
2.setUserVisibleHint里面的逻辑不明白是啥意思，能解释一下吗？
多谢！

**Comment by SkillCollege** [comment]
这些主要是为了当ViewPager包裹Fragment的时候，获得真正的Fragment的可见和不可见。防止界面重复调用onCreateView方法
