### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by nemati456** [SkillCollege/SimplifyReader#12]
Hi
i love your great project but i have a problem

would you Please translate your comments in English 
thanks alot

**Comment by SkillCollege** [comment]
Did you mean to translate the README.md in English??

**Comment by nemati456** [comment]
no for example 
public static final int MPM_RANDOM_PLAY = 3; // 随即播放

and add English Language in Strings.xml 

thanks a lot a we are waiting for new version 
thankas agian

**Comment by iluhcm** [comment]
see #32 , thanks.

**Comment by nemati456** [comment]
Thanks
