### ISSUE TITLE
魅族Note1移动开发版无法启动应用

### ISSUE THREAD

**Issue by Saxxhw** [SkillCollege/SimplifyReader#13]
我有两个测试机，一个是魅族Note1，一个是酷派大神F1(刷的MIUI)，在魅族手机上安装应用后无法打开，点击应用图标无法启动应用，在酷派手机上可正常打开应用，但是只有首次进入的时候可以正常获取数据，上下拉操作后就无法正常获取数据了。

**Comment by SkillCollege** [comment]
1. 魅族的可能是5.0的系统，有可能是so库的调用问题，你参考一下#issue7的解决方案能不能行
2.上下拉获取不了数据，你看看log打印，有没有调用获取数据的方法

**Comment by Saxxhw** [comment]
您好！参考#issue7的解决方案，魅族手机上的问题已经解决。（魅族手机还有个小问题是在首页无法退出应用，虚拟返回按钮被隐藏了，只能按home物理按键或直接杀死应用）
在酷派手机上调用了获取数据的方法，除了每次启动获取的一次数据之外，再次调用一直报timeout或“抱歉，系统出错了，请点击屏幕重试”的错误

**Comment by SkillCollege** [comment]
那个是我为了让所有手机都统一界面，魅族的那个SB我不是很喜欢，所以我隐藏掉了！！酷派的最好是能log自己调试一下，我这边没环境

**Comment by Saxxhw** [comment]
好滴，这两天正在看源码，再看看到底是哪里的原因导致获取不到数据。有没有可能是OKHTTP的问题？我记得原来好像有人说过OKHTTP在国内的部分手机上有时会获取不到数据，酷派好像就是。
