### ISSUE TITLE
20150916 pull到本地最新代码，报错

### ISSUE THREAD

**Issue by zolazhang** [SkillCollege/SimplifyReader#24]
/GitHub/SimplifyReader/library/src/main/java/com/github/obsessive/library/widgets/SmoothImageView.java:173: 错误: 找不到符号
        if (getDrawable() instanceof ColorDrawable) return;
                                     ^
  符号:   类 ColorDrawable
  位置: 类 SmoothImageView
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

:library:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by zolazhang** [comment]
import uk.co.senab.photoview.PhotoView;

缺少这个

**Comment by SkillCollege** [comment]
你下载的项目中是否依赖成功了PhotoView？

**Comment by wangchenghao** [comment]
里面没有导入ColorDrawable的类，导入后就不会出错了
