### ISSUE TITLE
com.afollestad.material-dialogs

### ISSUE THREAD

**Issue by langxuelang** [SkillCollege/SimplifyReader#33]
com.afollestad.material-dialogs，现在引用这个库，gradle里面好像不大对

这个库得加 maven { url "https://jitpack.io" }这个，它官方项目里面说的

**Comment by yanchenling** [comment]
这个问题解决了吗，我加上还是报错啊

**Comment by langxuelang** [comment]
解决了
    repositories {
        jcenter {
            url "http://jcenter.bintray.com/"
        }
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://raw.githubusercontent.com/umeng/mvn-repo-umeng/master/repository" }
    }

**Comment by yanchenling** [comment]
非常感谢！
