### ISSUE TITLE
Error retrieving parent for item

### ISSUE THREAD

**Issue by dylanchann** [SkillCollege/SimplifyReader#44]
导入项目的时候报错
log：
C:\Users\walmand_\Desktop\sample\SimplifyReader-master\library\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.0\res\values-v23\values-v23.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:Execution failed for task ':library:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\walmand_\AppData\Local\Android\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

项目的v7包明明用的是22的版本啊，本地也有22和23的版本，其他项目用22版本也没出现问题，网上的人都说compileSdk版本要跟v7包版本一致，我都是用的版本22啊

**Comment by SkillCollege** [comment]
所有的用最新的build一次试试

**Comment by dylanchann** [comment]
@SkillCollege android6.0SDK中删除HttpClient的相关类。。。所以也没办法用最新的平台编译，你的library里面引用了23版本的v7库资源，是不是问题出在这？

**Comment by dylanchann** [comment]
http://blog.csdn.net/yangqingqo/article/details/48214865
按上面方法导入org.apache.http.legacy.jar，重新clean build一次，还是不行
log如下：
   C:\Users\walmand_\Desktop\sample\SimplifyReader-master\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\res\values-ldltr-v21\values-ldltr-v21.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.
C:\Users\walmand_\Desktop\sample\SimplifyReader-master\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\res\values-ldrtl-v23\values-ldrtl-v23.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.
C:\Users\walmand_\Desktop\sample\SimplifyReader-master\app\build\intermediates\exploded-aar\SimplifyReader-master\library_youku\unspecified\res\values-v14\values-v14.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Holo.Light.DarkActionBar'.


所以是我的Android studio 的问题？

**Comment by dylanchann** [comment]
update：
MD-dialog 引用了23的资源，全部用23平台编译，因为API23删除HttpClient的相关类
所以要再library的gradle里面加上一行
android{
    useLibrary 'org.apache.http.legacy'
}

rebuild之后
splashActivity里面
    /*    AnalyticsConfig.setAppkey("55018d77fd98c5901e000a09");
        AnalyticsConfig.setChannel("SimplifyReader");*/
报错，然后我就注释掉了。。。（反正是友盟。。。不影响功能。。/尴尬脸）

然后就可以正常run了
