### ISSUE TITLE
编译library时找不到org.apache.http.XXX的方法。是不是gradle里少东西

### ISSUE THREAD

**Issue by shzyxk** [SkillCollege/SimplifyReader#46]
library编译出错。找不到org.apache.http.XXX的一些方法，是不是gradle里少了什么包
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:cardview-v7:23.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.jakewharton:butterknife:5.1.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'me.gujun.android.taggroup:library:1.4@aar'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    compile 'com.github.chrisbanes.photoview:library:1.2.2'
    compile 'com.afollestad:material-dialogs:0.7.9.1'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'

用的是 SDK 22 ，build-tools 是22.0.1，supportV7包是22.1.0

**Comment by SkillCollege** [comment]
新版本移除了httpclient，所以volley有问题了
