### ISSUE TITLE
导进去控制台报错了，帮忙看看

### ISSUE THREAD

**Issue by yyloveruancaipu** [SkillCollege/SimplifyReader#5]
Error:Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

**Comment by SkillCollege** [comment]
修改一下gradle的配置文件试试

**Comment by yyloveruancaipu** [comment]
已解决。装了JDK8就好了。。
