### ISSUE TITLE
Implements the BaseLazyFragment,but the method onFirstUserVisible() didn't execute

### ISSUE THREAD

**Issue by XinYiWorld** [SkillCollege/SimplifyReader#61]
public class HomeCenterFragment extends BaseFragment implements HomeCenterView{

    private HomeCenterPresenterImpl homeCenterPresenter;

    @Override
    protected void onFirstUserVisible() {
        homeCenterPresenter = new HomeCenterPresenterImpl(mContext, this);
        homeCenterPresenter.refreshData(false);
    }

    @Override
    protected void onUserVisible() {

    }

    @Override
    protected void onUserInvisible() {

    }

I'm writting a project which used your some classes,please write me back as soon as possible after you seen this,thanks!

**Comment by SkillCollege** [comment]
Make sure all classes are same with mine.

**Comment by XinYiWorld** [comment]
I  problely found the bug,your BaseLazyFragment is for ViewPager,but mine is Fragment hide and show,I have change a BaseFragment...

**Comment by zhangyuting11** [comment]
What BaseFragment have you changed?

发自我的 iPhone

**Comment by XinYiWorld** [comment]
I have replace your BaseLazyFragment with a fragment i have used before.
