### ISSUE TITLE
你好，请问是什么使你失去了维护该作品的动力？

### ISSUE THREAD

**Issue by walkthehorizon** [SkillCollege/SimplifyReader#78]
你写的这个应用蛮丰富的，使用到了很多开发的常用知识和第三方类库，首先表示感谢。以下纯属个人观点，

既然写出了该应用，为什么不保持维护和优化？我觉得可以适当削减功能，增加注释，清晰化应用结构，给其他开发者更好的学习样例不是更好么?

**Comment by woodgear** [comment]
楼上令人无语
代码就在那里 
不爽可以自己维护
这就是github的存在意义

**Comment by walkthehorizon** [comment]
抱歉，我的问法确实有些过于尖锐，所以以特别标明个人观点。但我并不觉得我的问题有什么过错,我仅仅是问作者为何放弃此库的维护原因，并无意责问改库作者，维护与否是作者本人的自由，所以我是“建议”既然已经完成该作，并产生了相当可观的围观者，如果条件允许还是希望作者愿意花时间进行一些必要的维护更新，也算是对该库和读者的负责，所以，以上仅是个人观点，无意掺杂中伤成分

**Comment by SkillCollege** [comment]
主要还是时间的原因导致了项目的搁浅，更大一部分原因是项目得到的反馈主要是一些编译不通过，项目运行报错这种本可以自己思考尝试解决的，可是偏偏更多的人是要一个提供完美适合他运行的结果，这样一个人，两个人都好解决，100个人就只能靠自己去思考了。
